# CI - Pipeline Integrada ao Build do Código
name: 'Execução Integrada Dinâmica'

# DEFINIÇÃO DOS GATILHOS (Triggers)

on:
  workflow_dispatch: # Gatilho Manual
  push:              # Gatilho por Push
    branches:
      - master
  # Gatilho Agendado (Ex: Toda segunda a sexta às 03:00 AM)
  schedule:
    - cron: '0 3 * * 1-5'

jobs:
  # INSPEÇÃO (Roda em QUALQUER um dos 3 gatilhos)

  inspecao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Inspeção de Código
        run: yarn lint

  # TESTES UNITÁRIOS (Roda apenas no PUSH e no MANUAL)

  unidade:
    runs-on: ubuntu-latest
    needs: [inspecao]

    # Não roda se for um evento agendado (schedule)

    if: github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Rodando testes unitários
        run: yarn run test

  # TESTES E2E (Roda apenas no AGENDADO e no MANUAL)

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [inspecao]

  # Não roda se for um push direto na master

    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Instalando Browsers do Playwright
        run: yarn playwright install
      - name: Executando testes E2E
        run: yarn run e2e
      - name: Salvando relatórios de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./playwright-report
          name: Relatório de Testes E2E

  # DEPLOY (Roda APENAS via PUSH ou MANUAL)

  deploy:
    runs-on: ubuntu-latest

    # O deploy aguarda os jobs que REALMENTE foram executados

    needs: [inspecao, unidade, e2e-tests]

    # Garante que o deploy não execute durante a rotina agendada (schedule)
   
    if: |
      always() &&
      github.event_name != 'schedule' &&
      (needs.unidade.result == 'success' || needs.unidade.result == 'skipped') &&
      (needs.e2e-tests.result == 'success' || needs.e2e-tests.result == 'skipped')
    steps:
      - name: Simulação de Deploy
        run: echo 'Deploy sendo realizado...'